### ISSUE TITLE
Fatal signal 6

### ISSUE THREAD

**Issue by daimoniuma** [Raslin777/XposedAdvancedLogging#4]
I finally tried to hook methods in specified class. And I got crash while hooked app execution.

```
--------- beginning of main
12-23 17:42:19.837 F/art     (14393): art/runtime/runtime.cc:287]   at java.lang.Daemons$FinalizerWatchdogDaemon.waitForObject(Daemons.java:239)
12-23 17:42:19.837 F/art     (14393): art/runtime/runtime.cc:287]   - locked <0x2bb785dd> (a java.lang.Daemons$FinalizerWatchdogDaemon)
12-23 17:42:19.837 F/art     (14393): art/runtime/runtime.cc:287]   at java.lang.Daemons$FinalizerWatchdogDaemon.run(Daemons.java:211)
12-23 17:42:19.837 F/art     (14393): art/runtime/runtime.cc:287]   at java.lang.Thread.run(Thread.java:818)
12-23 17:42:19.837 F/art     (14393): art/runtime/runtime.cc:287] 
12-23 17:42:19.837 F/art     (14393): art/runtime/runtime.cc:287] "HeapTrimmerDaemon" prio=5 tid=9 Waiting
12-23 17:42:19.837 F/art     (14393): art/runtime/runtime.cc:287]   | group="" sCount=0 dsCount=0 obj=0x12c051a0 self=0xa5e30c00
12-23 17:42:19.837 F/art     (14393): art/runtime/runtime.cc:287]   | sysTid=14406 nice=0 cgrp=apps sched=0/0 handle=0xb48ba780
12-23 17:42:19.837 F/art     (14393): art/runtime/runtime.cc:287]   | state=S schedstat=( 698907 0 4 ) utm=0 stm=0 core=3 HZ=100
12-23 17:42:19.837 F/art     (14393): art/runtime/runtime.cc:287]   | stack=0xb02fe000-0xb0300000 stackSize=1036KB
12-23 17:42:19.837 F/art     (14393): art/runtime/runtime.cc:287]   | held mutexes=
12-23 17:42:19.837 F/art     (14393): art/runtime/runtime.cc:287]   kernel: (couldn't read /proc/self/task/14406/stack)
12-23 17:42:19.837 F/art     (14393): art/runtime/runtime.cc:287]   native: #00 pc 00010294  /system/lib/libc.so (syscall+28)
12-23 17:42:19.837 F/art     (14393): art/runtime/runtime.cc:287]   native: #01 pc 000aafcb  /system/lib/libart.so (art::ConditionVariable::Wait(art::Thread*)+82)
12-23 17:42:19.837 F/art     (14393): art/runtime/runtime.cc:287]   native: #02 pc 001e4e7f  /system/lib/libart.so (art::Monitor::Wait(art::Thread*, long long, int, bool, art::ThreadState)+1006)
--------- beginning of crash
12-23 17:42:19.853 F/libc    (14393): Fatal signal 6 (SIGABRT), code -6 in tid 14393 (apk.noname)
12-23 17:42:19.853 I/libc    (14393): Suppressing debuggerd output because prctl(PR_GET_DUMPABLE)==0
12-23 17:42:19.901 I/Zygote  (318): Process 14393 exited due to signal (6)
12-23 17:42:19.911 I/ActivityManager(1480): Process no.name.apk (pid 14393) has died
```

**Comment by Raslin777** [comment]
This looks like it is from native hooking? If so can you make sure that your hooked app has sdcard access, if not you can inject it.

**Comment by daimoniuma** [comment]
This app doesn't consist .so libs, if you meant it. Moreover, it is Xposed module. I'm not sure about external SD access, because it is fully unlocked. I'm on Android L, so there is no permissions settings like in M. I can't inject anything in this app, because it isn't mine. Anyway this app works well without hook from you and crash at start with...

**Comment by Raslin777** [comment]
I don't think you understand. There are 2 different hooking methods going on here. First you have the xposed hooking with hooking and dumping classes and methods. Then you have native hooking via libc.so. this is a Android/Linux library that typically cannot be hooked by xposed. Thats the reason for library error. The reason why I said the application you hook needs write card access is for accessing the hooking information. Due to being in the hook(app) before we can access the information of what we need to hook. This is because it's loaded before the application even runs. So only way is to access it though a common accessible location aka the sdcard. also note hooking errors are going to be very different on different apps and phones. Due to protections and architectures. If you have a better method for importing settings into native hooks I'm very open to it. Haven't found a better way yet. Anyhow thank you for the feed back and if you still have issues please detail your settings, options and logcats if possible. Keep in mind this is very lowlevel hooking so you have to have a very good understanding of how this works.

**Comment by Raslin777** [comment]
![screenshot_20161229-192642](https://cloud.githubusercontent.com/assets/6191287/21557608/e28d89da-cdfc-11e6-9f57-4b2059eea83a.png)
Here is a screenshot of native hooking of libc.so via "open" dumping the parameter.

**Comment by daimoniuma** [comment]
Are you told about /data/data/adv.log/classes.txt (info of what we need to hook)? I just created empty file, didn't setup permissions / owners.

**Comment by daimoniuma** [comment]
Hooked app have android.permission.READ_EXTERNAL_STORAGE.
